Repository saumyayadav25/cpp-dsa-sheet-testing, pull requests merged in 2025-08, with the labels that each got.

#125 Updated CONTRIBUTING.md with local setup guide
  CONTRIBUTING.md
  package-lock.json
Labels: GSSoC25, level-2

#130 Add sound on POTD mark as done
  components/POTD.tsx
  package-lock.json
  package.json
  public/sounds/done.mp3
Labels: GSSoC25, level-1

#146 Follow up Fix #145 PR Quiz background Fix
  app/timequiz/page.tsx
Labels: GSSoC25, level-1

#148 Enhanced Toast mssgs for login/signup
  app/(auth)/sign-in/page.tsx
  app/(auth)/sign-up/page.tsx
  package-lock.json
  package.json
Labels: GSSoC25, level-2

#159 #103.1
  app/(auth)/resetPassword/page.tsx
  app/(auth)/sign-in/page.tsx
  app/layout.tsx
  components/FooterWrapper.tsx
Labels: GSSoC25, level-2

#123 docs: add links to footer
  app/privacy-terms/page.tsx
  components/Footer.tsx
Labels: GSSoC25, level-3

#163 Implement Dynamic Badge System for User Milestones and Progress
  app/api/badges/[userId]/route.ts
  app/api/badges/route.ts
  app/profile/[userId]/page.tsx
  components/AuthButtons.tsx
  components/POTD.tsx
  components/SheetContent.tsx
  package-lock.json
Labels: GSSoC25, level-3

#164 Add DSAMate Logo (Light & Dark Mode) + Source File
  design/logo-submissions/Harshit_Sharma/README.md
  design/logo-submissions/Harshit_Sharma/idea_dark.png
  design/logo-submissions/Harshit_Sharma/idea_dark.svg
  design/logo-submissions/Harshit_Sharma/idea_light.png
  design/logo-submissions/Harshit_Sharma/idea_light.svg
  design/logo-submissions/Harshit_Sharma/logo.fig
Labels: GSSoC25, level-1

#166 Fix: Sign In Button Flicker on Hover
  components/AuthButtons.tsx
Labels: GSSoC25, level-1

#175 Add Social Sharing Buttons for Achievement Badges (LinkedIn & Twitter)
  app/profile/[userId]/Button.tsx
  app/profile/[userId]/page.tsx
Labels: GSSoC25, level-2

#178 issue create automate message added
  .github/workflows/issue-create-automate-message.yml
Labels: GSSoC25, level-1

#179 added searchbar and favourites in notes
  app/notes/page.tsx
  package-lock.json
  package.json
Labels: GSSoC25, level-2

#187 Fix: Improve text contrast for "Visit Profile" and "Visit Original DSAMate" in light mode
  app/contributors/page.tsx
  app/page.tsx
Labels: GSSoC25, level-1

#189 Fix: Navbar Visibility on Sheet Page
  components/NavbarSheet.tsx
Labels: GSSoC25, level-1

#194 Following up previous PR Secure Daily POTD Emails
  .github/workflows/send-potd.yml
  app/api/send-potd/route.ts
  models/JobRun.model.ts
Labels: GSSoC25, level-2

#195 Adding graphical stats such as rating progression, spider map for codeforces
  app/cp-tracker/page.tsx
  components/CodeforcesCharts.tsx
  components/charts/DifficultyBarChart.tsx
  components/charts/RatingChart.tsx
  components/charts/RatingProgression.tsx
  components/charts/TagsPieChart.tsx
  components/charts/TopicRadarChart.tsx
  package-lock.json
  package.json
  tsconfig.json
  utils/codeforces.ts
Labels: GSSoC25, level-3

#196 Add Profile picture feature
  app/api/avatar/route.ts
  app/profile_pic/settings/avatar/page.tsx
  components/AuthButtons.tsx
  models/User.model.ts
  public/images/default-avatar.png
Labels: GSSoC25, level-3

#206 Following up previous merge #196
  components/AuthButtons.tsx
Labels: GSSoC25, level-1

#211 Added border radius for nested div
  components/SheetContent.tsx
Labels: GSSoC25, level-1

#210 Global Streak Synchronization Across Navbar & Pages
  app/api/progress/[userId]/route.ts
  app/contributors/page.tsx
  app/cp-tracker/page.tsx
  app/notes/page.tsx
  app/page.tsx
  app/privacy-terms/page.tsx
  app/profile/[userId]/page.tsx
  app/profile_pic/settings/avatar/page.tsx
  app/progress/page.tsx
  app/sheet/page.tsx
  app/timequiz/page.tsx
  components/AuthButtons.tsx
  components/Navbar.tsx
  components/NavbarSheet.tsx
Labels: GSSoC25, level-2

#213 Integrated Gemini API for dynamic quiz generation (with new questions each time) & instant feedback
  app/api/generate-feedback/route.ts
  app/api/generate-quiz/route.ts
  app/timequiz/TimeQuiz.module.css
  app/timequiz/page.tsx
Labels: GSSoC25, level-3

#224 fix: Single FAQ expanded at a time
  app/page.tsx
Labels: GSSoC25, level-1

#229 feat: add scroll-to-top and scroll-to-bottom buttons; reposition 'Rep…
  app/api/contributors-points/route.ts
  app/page.tsx
  components/AuthButtons.tsx
  components/BotWidget.tsx
  components/ReportIssueButton.tsx
  components/ScrollToTopBottom.tsx
  components/ui/card-spotlight.tsx
  package-lock.json
  package.json
Labels: GSSoC25, level-1

#235 Implemented quiz backend frontend
  app/api/quiz-results/[userId]/recent/route.ts
  app/api/quiz-results/[userId]/route.ts
  app/api/quiz-results/[userId]/stats/route.ts
  app/api/quiz-results/route.ts
  app/timequiz/TimeQuiz.module.css
  app/timequiz/page.tsx
  models/quizSchema.ts
Labels: GSSoC25, level-3

#237 Fix: ScrollToTopBottom button appears on all pages
  app/layout.tsx
  components/ScrollToTopBottom.tsx
Labels: GSSoC25, level-1

#239 Implmented Dynamic-Testimonial-System
  app/api/testimonial/post/route.ts
  app/api/testimonial/route.ts
  app/page.tsx
  components/MarqueeDemo.tsx
  models/Testimonials.ts
Labels: GSSoC25, level-3

#252 Added validation in sheet page
  components/POTD.tsx
  components/SheetContent.tsx
Labels: GSSoC25, level-3

#263 Added the similar modal for form of testimonial response taker from user
  app/globals.css
  app/page.tsx
  components/AuthButtons.tsx
Labels: GSSoC25, level-3

#264 Added filter for supereme 3.0 and pattern wise notes in notes page
  app/notes/page.tsx
Labels: GSSoC25, level-2

#262 Fix: Added the back navigation in quiz with prompting
  app/timequiz/page.tsx
Labels: GSSoC25, level-2
