Repository saumyayadav25/cpp-dsa-sheet-testing, pull requests merged in 2025-07, with the labels that each got.

#8 Update navbar across all screen
  .gitignore
  app/notes/page.tsx
  app/page.tsx
  app/sheet/page.tsx
  components/Navbar.tsx
Labels: enhancement, GSSoC'25, level-2

#14 Fixed: Filter Section Dropdown Items Are Invisible Unless Hovered
  app/sheet/page.tsx
Labels: GSSoC'25, level-1

#18 Enhancement: Navbar Styling and Transitions
  components/AuthButtons.tsx
  components/Navbar.tsx
  package-lock.json
  package.json
Labels: enhancement, GSSoC'25, level-2

#20 Update README: Added Contributors Section
  README.md
Labels: documentation, GSSoC'25, level-1

#50 fix: remove duplicate footer on Progress page
  Frontend/app/progress/page.tsx
Labels: GSSoC'25, level-1

#56 [Feat] : Implemented Backend in Nextjs with User Authentication
  Frontend/.env
  Frontend/app/api/auth/login/route.ts
  Frontend/app/api/auth/me/route.ts
  Frontend/app/api/auth/register/route.ts
  Frontend/app/login/page.tsx
  Frontend/app/register/page.tsx
  Frontend/components/AuthButtons.tsx
  Frontend/lib/dbConnect.ts
  Frontend/models/User.ts
  Frontend/package-lock.json
  Frontend/package.json
Labels: enhancement, GSSoC'25, level-3

#72 docs: added MIT license to README
  README.md
Labels: documentation, GSSoC'25, level-1

#68 Added a custom logo for DSAMate
  Frontend/design/logo-submissions/nikhithars/README.md
  Frontend/design/logo-submissions/nikhithars/favicon.png
  Frontend/design/logo-submissions/nikhithars/icon-dark.png
  Frontend/design/logo-submissions/nikhithars/icon-light.png
Labels: GSSoC'25, level-1

#69 Environment Variable Setup & OAuth Configuration
  Frontend/.env
  Frontend/.gitignore
  Frontend/app/(auth)/changePassword/changePassword.tsx
  Frontend/app/(auth)/changePassword/page.tsx
  Frontend/app/(auth)/layout.tsx
  Frontend/app/(auth)/resetPassword/page.tsx
  Frontend/app/(auth)/sign-in/page.tsx
  Frontend/app/(auth)/sign-up/page.tsx
  Frontend/app/api/(auth)/changePassword/route.ts
  Frontend/app/api/(auth)/check-auth/route.ts
  Frontend/app/api/(auth)/forgotPassword/route.ts
  Frontend/app/api/(auth)/github/callback/route.ts
  Frontend/app/api/(auth)/github/route.ts
  Frontend/app/api/(auth)/google/callback/route.ts
  Frontend/app/api/(auth)/google/route.ts
  Frontend/app/api/(auth)/logout/route.ts
  Frontend/app/api/(auth)/resendOtp/route.ts
  Frontend/app/api/(auth)/sign-in/route.ts
  Frontend/app/api/(auth)/sign-up/route.ts
  Frontend/app/api/(auth)/signIn-verify-Otp/route.ts
  Frontend/app/api/(auth)/verify-otp/route.ts
  Frontend/app/api/(auth)/verifyForgotPassOtp/route.ts
  Frontend/app/api/auth/login/route.ts
  Frontend/app/api/auth/me/route.ts
  Frontend/app/api/auth/register/route.ts
  Frontend/app/globals.css
  Frontend/app/login/page.tsx
  Frontend/app/register/page.tsx
  Frontend/components/AuthButtons.tsx
  Frontend/components/OAuthLogin.tsx
  Frontend/components/ui/dialog.tsx
  Frontend/components/ui/input-otp.tsx
  Frontend/components/ui/input.tsx
  Frontend/components/ui/sonner.tsx
  Frontend/components/verify-otp.tsx
  Frontend/constant/dbName.ts
  Frontend/db/config.ts
  Frontend/lib/dbConnect.ts
  Frontend/lib/mail.ts
  Frontend/lib/sendOTP.ts
  Frontend/lib/utils.ts
  Frontend/models/User.model.ts
  Frontend/models/User.ts
  Frontend/next.config.ts
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/public/assets/github.png
  Frontend/public/assets/google.png
Labels: enhancement, GSSoC'25, level-3

#76 Changed Contributing.md
  CONTRIBUTING.md
Labels: GSSoC'25, level-1

#81 Added light/dark variants of logo and favicon + added the design source file
  design/logo-submissions/Prajanya/DSAMate_logo.ai
  design/logo-submissions/Prajanya/Design_specification.md
  design/logo-submissions/Prajanya/Logo_dark.png
  design/logo-submissions/Prajanya/Logo_favicon_dark.png
  design/logo-submissions/Prajanya/Logo_favicon_light.png
  design/logo-submissions/Prajanya/Logo_light.png
Labels: GSSoC'25, level-1

#92 Input text Visibility fixed
  components/ui/input.tsx
Labels: GSSoC'25, level-1

#96 Fix: Unified Navbar and Enhanced Notes Cards UI
  app/notes/page.tsx
  app/progress/page.tsx
  app/sheet/page.tsx
  components/AuthButtons.tsx
  components/Navbar.tsx
  components/NavbarSheet.tsx
Labels: enhancement, GSSoC25, level-2

#104 homepage refactor-changed complete UI for the homepage
  app/page.tsx
  public/bg.png
  public/dsa-hero.png
Labels: enhancement, GSSoC25, level-3

#107 Added DSA_Mate_logo
  design/logo-submissions/Mevishf/DSA_Mate_darkmode.png
  design/logo-submissions/Mevishf/DSA_Mate_lightmode.png
  design/logo-submissions/Mevishf/README.md
  design/logo-submissions/Mevishf/favicon-dark(16x16).png
  design/logo-submissions/Mevishf/favicon-dark(32x32).png
  design/logo-submissions/Mevishf/favicon-light(16x16).png
  design/logo-submissions/Mevishf/favicon-light(32x32).png
Labels: GSSoC25, level-1

#109 Send Daily POTD notifications to registered emails.
  .github/workflows/send-potd.yml
  app/api/email-preference/route.ts
  app/api/send-potd/route.ts
  app/email-preference/content.tsx
  app/email-preference/page.tsx
  models/User.model.ts
Labels: GSSoC25, level-3

#108 Modified Contributors Page [#Issue 101]
  app/api/contributors-points/route.ts
  app/contributors/page.tsx
  package-lock.json
Labels: GSSoC25, level-2
