Repository saumyayadav25/cpp-dsa-sheet-testing, pull requests merged in 2025-09, with the labels that each got.

#260 Fixed the mobile view nav links issue
  components/AuthButtons.tsx
Labels: GSSoC25, level-1

#270 fix: improve footer styling consistency with design system
  components/Footer.tsx
Labels: GSSoC25, level-2

#271 fix: resolve light mode dropdown menu theme inconsistency
  components/AuthButtons.tsx
Labels: GSSoC25, level-1

#285 Feat: Add Company-wise Questions Page (Fixes #112)
  app/companies/page.tsx
  app/layout.tsx
  components/CompanyProgressSummary.tsx
  components/CompanyQuestionsList.tsx
  components/CompanySelector.tsx
  components/Navbar.tsx
  contexts/QuestionContext.tsx
  data/companyQuestions.ts
Labels: GSSoC25, level-3

#287 Resolved vercel conflicts
  app/(auth)/changePassword/changePassword.tsx
  app/code-analyzer/layout.tsx
  app/code-analyzer/page.tsx
  app/email-preference/content.tsx
  app/privacy-terms/page.tsx
  app/question/[slug]/page.tsx
  lib/openaiAnalyze.ts
  package-lock.json
  package.json
  pages/api/openai-analyze.ts
  tsconfig.json
Labels: GSSoC25, level-3

#274 Added animated multi-topic progress tracker
  app/progress/progressbar/progressbar.html
  components/ProgressTracker.tsx
  components/SheetContent.tsx
  package-lock 2.json
  package-lock.json
  package.json
Labels: GSSoC25, level-1

#299 fix: dropdown options visibility in light/dark mode
  app/code-analyzer/page.tsx
Labels: GSSoC25, level-1

#296 fix: resolve critical flashcard UI corruption and data rendering issues
  app/globals.css
  components/FlashcardComponent.tsx
Labels: GSSoC25, level-1

#300 Fix: Navbar overlaps page header on mobile viewports in /sheet page
  app/globals.css
  app/sheet/page.tsx
  components/NavbarSheet.tsx
Labels: GSSoC25, level-1

#317 Added Code Analyzer page with Time & Space Complexity, updated navbar…
  app/code-analyzer/page.tsx
  tsconfig.json
Labels: GSSoC25, level-2

#327 feat: Enhanced Code Analyzer Page with Modern UI
  app/code-analyzer/layout.tsx
  app/code-analyzer/page.tsx
Labels: GSSoC25, level-1

#333 feat: Added Questions API, Integrated with frontend
  app/api/questions/route.ts
  app/api/test/route.ts
  app/sheet/page.tsx
  app/test-api/page.tsx
  components/SheetContent.tsx
  db/config.ts
  debug-api.js
  lib/questionsApi.ts
  lib/questionsApiExamples.ts
  models/Question.model.ts
  package.json
  scripts/seedQuestions.ts
Labels: GSSoC25, level-3

#334 feat: Added Post Route for questions
  app/(auth)/layout.tsx
  app/api/questions/README.md
  app/api/questions/route.ts
Labels: GSSoC25, level-3

#342 [Feature]: Remove old buttons & rename DSAMate Template → DSAMate v2
  README.md
  app/page.tsx
  app/privacy-terms/page.tsx
  app/sheet/page.tsx
  components/Footer.tsx
  components/NavbarSheet.tsx
Labels: GSSoC25, level-2

#343 [update]-updated the readme.md learn.md files according to the project requirements.
  LEARN.md
  README.md
Labels: GSSoC25, level-1

#340 updated toggle eye icon
  app/(auth)/sign-in/page.tsx
  app/(auth)/sign-up/page.tsx
Labels: GSSoC25, level-1

#336 feat: add text styling tools (bold, italics, bullets, headings) in No…
  app/api/questions/route.ts
  components/RichTextEditor.tsx
  components/SheetContent.tsx
  db/config.ts
  package-lock.json
Labels: GSSoC25, level-3

#363 Hover animation added to the button
  app/notes/page.tsx
Labels: GSSoC25, level-1

#368 feat: Made Question fetch in sorted order
  app/api/questions/route.ts
  components/SheetContent.tsx
  db/config.ts
Labels: GSSoC25, level-1

#369 hover aniamtion added on the dropdown buttons of sheet section
  app/sheet/SheetPageClient.tsx
Labels: GSSoC25, level-1

#357 Enhance pwa manifest and favicon system for better scalability and performance
  PWA-SETUP.md
  app/layout.tsx
  package.json
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-48x48.png
  public/favicon-config.json
  public/favicon.ico
  public/icons/apple/apple-touch-icon-114x114.png
  public/icons/apple/apple-touch-icon-120x120.png
  public/icons/apple/apple-touch-icon-144x144.png
  public/icons/apple/apple-touch-icon-152x152.png
  public/icons/apple/apple-touch-icon-180x180.png
  public/icons/apple/apple-touch-icon-57x57.png
  public/icons/apple/apple-touch-icon-60x60.png
  public/icons/apple/apple-touch-icon-72x72.png
  public/icons/apple/apple-touch-icon-76x76.png
  public/icons/icon-128x128.png
  public/icons/icon-144x144.png
  public/icons/icon-152x152.png
  public/icons/icon-192x192-maskable.png
  public/icons/icon-192x192.png
  public/icons/icon-384x384.png
  public/icons/icon-512x512-maskable.png
  public/icons/icon-512x512.png
  public/icons/icon-72x72.png
  public/icons/icon-96x96.png
  public/icons/microsoft/mstile-144x144.png
  public/icons/microsoft/mstile-150x150.png
  public/icons/microsoft/mstile-310x150.png
  public/icons/microsoft/mstile-310x310.png
  public/icons/microsoft/mstile-70x70.png
  public/icons/shortcut-flashcards.png
  public/icons/shortcut-practice.png
  public/icons/shortcut-progress.png
  public/icons/shortcuts/shortcut-flashcards.png
  public/icons/shortcuts/shortcut-practice.png
  public/icons/shortcuts/shortcut-progress.png
  public/manifest.json
  public/screenshots/desktop-screenshot.png
  public/screenshots/mobile-screenshot.png
  public/sw-enhanced.js
  pwa-validation-report.json
  scripts/generate-icons-from-fav.js
  scripts/pwa-validator.js
Labels: GSSoC25, level-2
