Repository saumyayadav25/cpp-dsa-sheet-testing, pull requests merged in 2025-10, with the labels that each got.

#374 Fix: Replace Total Active Days with Total Submissions across all CP platforms
  app/cp-tracker/CPTrackerPageClient.tsx
  utils/leetcode.ts
Labels: GSSoC25, level-1

#375 Fix progress sync
  app/api/progress/[userId]/route.ts
  app/api/progress/update/route.ts
  app/progress/ProgressPageClient.tsx
  app/sheet/SheetPageClient.tsx
  components/ProgressStats.tsx
  components/ProgressSummary.tsx
  components/SheetContent.tsx
  components/TopicProgress.tsx
  models/Progress.model.ts
Labels: GSSoC25, level-1

#370 updated botwidget responsiveness for all screentype
  app/globals.css
  components/BotWidget.tsx
Labels: GSSoC25, level-1

#387 add logo design by Karan R
  design/logo-submissions/Karan_R/README.md
  design/logo-submissions/Karan_R/dsa_mate_dark.png
  design/logo-submissions/Karan_R/dsa_mate_dark_notext.png
  design/logo-submissions/Karan_R/dsa_mate_light.png
  design/logo-submissions/Karan_R/dsa_mate_light_notext.png
Labels: GSSoC25, level-1

#396 Added new Flashcards
  components/mode-toggle.tsx
  components/ui/conceptCard.tsx
  data/flashcards.ts
Labels: GSSoC25, level-1, hacktoberfest-accepted

#397 [ENH]: Enchanced code analyzer page
  app/code-analyzer/layout.tsx
  app/code-analyzer/page.tsx
Labels: GSSoC25, level-3, hacktoberfest-accepted

#398 [FEAT]: Sync POTD and Mark as Done
  components/POTD.tsx
  components/SheetContent.tsx
Labels: GSSoC25, level-3, hacktoberfest-accepted

#393 bug: fixed issue in testimonial form and made the additional feedback optional
  app/api/testimonial/post/route.ts
  app/code-analyzer/page.tsx
  app/layout.tsx
  app/page.tsx
  models/Testimonials.ts
Labels: GSSoC25, level-2, hacktoberfest-accepted

#419 Update header UI and recent attempts section
  app/api/generate-feedback/route.ts
  app/api/generate-quiz/route.ts
  app/api/progress/[userId]/route.ts
  app/api/progress/update/route.ts
  app/api/quiz-results/[userId]/recent/route.ts
  app/api/quiz-results/[userId]/stats/route.ts
  app/timequiz/page.tsx
  models/Progress.model.ts
Labels: GSSoC25, level-1
